In [1]:
import pandas as pd
pd.set_option('display.max_colwidth',None)

### Model Evaluation

#Embedding models_ 1: 

EMBEDDING_MODEL_NAME: str = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"

EVALUATION_EMBEDDING_MODEL_NAME: str = "BAAI/bge-large-en-v1.5"

#Embedding models_ 2: 

EMBEDDING_MODEL_NAME: str = "BAAI/bge-large-en-v1.5"

EVALUATION_EMBEDDING_MODEL_NAME: str ="Qwen/Qwen3-Embedding-0.6B"

In [ ]:
### Results from Embedding models_ 1: 
sum_results_df=pd.read_csv('../evaluation/evaluation_results/baseline_evaluation_summary_2026-10-09_11-34-36.csv')
sum_results_df

,chunk_size,chunk_overlap,faithfulness,answer_correctness,context_precision,context_recall
0,450,50,0.878788,0.660347,1.0,1.0

In [ ]:
### Results from Embedding models_2:
sum2_results_df=pd.read_csv('../evaluation/evaluation_results/baseline_evaluation_summary_2026-10-09_13-18-09.csv')
sum2_results_df

,chunk_size,chunk_overlap,faithfulness,answer_correctness,context_precision,context_recall
0,450,50,0.714286,0.661295,1.0,1.0

### Chunking strategy

In [ ]:
### using Model_2
sum_chunk_df=pd.read_csv('../evaluation/evaluation_results/chunking_evaluation_summary_2026-10-09_14-06-16.csv')
sum_chunk_df

,chunk_size,chunk_overlap,faithfulness,answer_correctness,context_precision,context_recall
0,250,40,0.846154,0.665853,1.0,NaN
1,350,60,0.880000,0.456203,NaN,0.0
2,512,80,0.857143,0.538916,NaN,1.0

In [7]:
sum2_chunk_df=pd.read_csv('../evaluation/evaluation_results/chunking_evaluation_summary_2026-10-09_14-23-30.csv')
sum2_chunk_df

,chunk_size,chunk_overlap,faithfulness,answer_correctness,context_precision,context_recall
0,250,40,0.760000,0.679299,1.0,1.0
1,350,60,0.818182,NaN,1.0,0.0
2,512,80,0.827586,0.664710,NaN,1.0

In [ ]:
### using Model 1
sum3_chunk_df=pd.read_csv('../evaluation/evaluation_results/chunking_evaluation_summary_2026-10-09_14-51-15.csv')
sum3_chunk_df

,chunk_size,chunk_overlap,faithfulness,answer_correctness,context_precision,context_recall
0,250,40,1.000000,0.510459,0.958333,1.0
1,350,60,0.880000,0.626998,0.958333,1.0
2,512,80,0.914286,0.531148,0.916667,1.0

### Reranking Stratergy

In [9]:
### using Model 1

sum_rerank_df=pd.read_csv('../evaluation/evaluation_results/reranker_evaluation_summary_2026-10-09_15-25-50.csv')
sum_rerank_df

,chunk_size,chunk_overlap,retriever_k,reranker_n,faithfulness,answer_correctness,context_precision,context_recall
0,350,60,10,2,0.818182,0.557920,1.0,0.0
1,350,60,10,5,0.730769,0.646298,1.0,1.0
2,350,60,20,5,0.652174,0.683326,1.0,1.0

### Query Rewrite stratergy(HyDE)

In [ ]:
### Model 1
sum_query_rewrite_df=pd.read_csv('../evaluation/evaluation_results/query_rewrite_evaluation_summary_2026-10-09_16-17-01.csv')
sum_query_rewrite_df

,chunk_size,chunk_overlap,retriever_k,reranker_n,use_hyde,faithfulness,answer_correctness,context_precision,context_recall
0,350,60,20,5,False,0.740741,0.662114,NaN,NaN
1,350,60,20,5,True,NaN,NaN,NaN,NaN

In [11]:
sum2_query_rewrite_df=pd.read_csv('../evaluation/evaluation_results/query_rewrite_evaluation_summary_2026-10-11_13-44-19.csv')
sum2_query_rewrite_df

,chunk_size,chunk_overlap,retriever_k,reranker_n,use_hyde,faithfulness,answer_correctness,context_precision,context_recall
0,350,60,20,5,False,0.740741,0.661644,NaN,1.0
1,350,60,20,5,True,0.857143,0.731540,1.0,1.0